language: python
python: 3.6


install:
  - pip install requests

script:
  - ./main.py


env:
  # $GITHUB_TOKEN environment variable
  # Currently a `public_repo` token of `pietroalbini-cat`
  - name: "botman"

notifications:
  email: false
